services:
  # Backend API Service
  - type: web
    name: renova-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: renova-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://renova.vercel.app

  # PostgreSQL Database
  - type: pserv
    name: renova-db
    env: postgresql
    plan: free
    databaseName: renova
    databaseUser: renova_user
