services:
  - type: web
    name: renova-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: renova-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://renova.vercel.app

databases:
  - name: renova-db
    databaseName: renova
    user: renova_user
